### ISSUE TITLE
Dont Work with core-2022.3.3

### ISSUE THREAD

**Issue by jovanotti25** [marotoweb/home-assistant-vacuum-viomise#16]
Turn vacuum unavailable

**Comment by kamwill** [comment]
I have the same issue, with following error Platform error vacuum.viomise - cannot import name 'Vacuum' from 'miio' (/usr/local/lib/python3.9/site-packages/miio/__init__.py)

**Comment by AybimYazilim** [comment]
Change 6. line in vacuum.py file  from 

`from miio import DeviceException, Vacuum  # pylint: disable=import-error`
to
`from miio import ViomiVacuum, DeviceException # pylint: disable=import-error`


and change 165. line from

`    vacuum = Vacuum(host, token)`
to
`    vacuum = ViomiVacuum(host, token)`


then restart to home assistant. it will work.

**Comment by le-vive** [comment]
Still get the issue: **core-2022.4.2**


configuration validation's error:

> Platform error vacuum.viomise - cannot import name 'Vacuum' from 'miio' (/usr/local/lib/python3.9/site-packages/miio/__init__.py)

I did no change from the configuration.yaml, only update the core (so the config should be still good).

**Comment by jovanotti25** [comment]
> Still get the issue: **core-2022.4.2**
> 
> configuration validation's error:
> 
> > Platform error vacuum.viomise - cannot import name 'Vacuum' from 'miio' (/usr/local/lib/python3.9/site-packages/miio/**init**.py)
> 
> I did no change from the configuration.yaml, only update the core (so the config should be still good).

try to make 

Change 6. line in vacuum.py file from

from miio import DeviceException, Vacuum # pylint: disable=import-error
to
from miio import ViomiVacuum, DeviceException # pylint: disable=import-error

and change 165. line from

vacuum = Vacuum(host, token)
to
vacuum = ViomiVacuum(host, token)

then restart to home assistant. it will work.

**Comment by moshriq** [comment]
@AybimYazilim Thanks for suggested solution, is there any a way to make it work with an offline vacuum?  it only work if i'ts connected to internet
